### ISSUE TITLE
INVALID_ARGUMENT

### ISSUE THREAD

**Issue by smatisen** [grammyjs/storages#167]
After I managed to install this plugin, my bot completely stop working the way it ws before. Crash after crash. I`m not sure if I should not use it or can it be fixed is some way?

Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value. at callErrorFromStatus 

DEFAULT 2023-03-02T12:46:16.591903Z [resource.labels.functionName: valimisedBot] [labels.executionId: 1u84fc1geo2s] at /workspace/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:225:29

 Caused by: Error
DEFAULT 2023-03-02T12:46:16.591951Z [resource.labels.functionName: valimisedBot] [labels.executionId: 1u84fc1geo2s] at WriteBatch.commit (/workspace/node_modules/@google-cloud/firestore/build/src/write-batch.js:433:23)
DEFAULT 2023-03-02T12:46:16.591956Z [resource.labels.functionName: valimisedBot] [labels.executionId: 1u84fc1geo2s] at DocumentReference.set (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:392:27)
DEFAULT 2023-03-02T12:46:16.591961Z [resource.labels.functionName: valimisedBot] [labels.executionId: 1u84fc1geo2s] at Object.write (/workspace/node_modules/@grammyjs/storage-firestore/dist/cjs/index.js:11:39)
DEFAULT 2023-03-02T12:46:16.591968Z [resource.labels.functionName: valimisedBot] [labels.executionId: 1u84fc1geo2s] at PropertySession.finish (/workspace/node_modules/grammy/out/convenience/session.js:232:40)

DEBUG 2023-03-02T12:46:16.598473367Z [resource.labels.functionName: valimisedBot] [labels.executionId: 1u84fc1geo2s] Function execution took 1877 ms, finished with status: 'crash'

**Comment by KnorpelSenf** [comment]
Is this still relevant?
